# Generated by Django 4.2.5 on 2023-10-01 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        ('stock', '0002_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='wallet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='wallet.wallet'),
            preserve_default=False,
        ),
    ]
