# Generated by Django 4.2.5 on 2023-10-01 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        ('stock', '0004_alter_stock_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='wallet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wallet.wallet'),
        ),
    ]
